/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class ApplicationPlan extends Object {


    /**
     * 
     */
	 private Double subscription_period_charge ;

    /**
     * 
     */
	 private Integer product_id ;

    /**
     * 
     */
	 private String description ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private Integer application_id ;

    /**
     * 
     */
	 private String currency_code ;


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getSubscription_period_charge() {
	 	return subscription_period_charge;
	 }  
	 
	 public void setSubscription_period_charge(Double  subscription_period_charge) {
	 	this.subscription_period_charge = subscription_period_charge;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getProduct_id() {
	 	return product_id;
	 }  
	 
	 public void setProduct_id(Integer  product_id) {
	 	this.product_id = product_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getDescription() {
	 	return description;
	 }  
	 
	 public void setDescription(String  description) {
	 	this.description = description;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getApplication_id() {
	 	return application_id;
	 }  
	 
	 public void setApplication_id(Integer  application_id) {
	 	this.application_id = application_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrency_code() {
	 	return currency_code;
	 }  
	 
	 public void setCurrency_code(String  currency_code) {
	 	this.currency_code = currency_code;
	 }


}