/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class ApplicationInCompanyResponse extends Object {



    /**
     * 
     */
	 private Integer id ;


    /**
     * 
     */
	 private java.util.Date added ;


    /**
     * 
     */
	 private java.util.Date updated ;


    /**
     * 
     */
	 private Boolean active ;


    /**
     * 
     */
	 private Integer application_id ;



	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return id;
	 }  
	 
	 public void setId(Integer  id) {
	 	this.id = id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getAdded() {
	 	return added;
	 }  
	 
	 public void setAdded(java.util.Date  added) {
	 	this.added = added;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getUpdated() {
	 	return updated;
	 }  
	 
	 public void setUpdated(java.util.Date  updated) {
	 	this.updated = updated;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getActive() {
	 	return active;
	 }  
	 
	 public void setActive(Boolean  active) {
	 	this.active = active;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getApplication_id() {
	 	return application_id;
	 }  
	 
	 public void setApplication_id(Integer  application_id) {
	 	this.application_id = application_id;
	 }


}