/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class CompanyInfoRequest extends Object {


    /**
     * 
     */
	 private String timezone ;

    /**
     * 
     */
	 private String phone ;

    /**
     * 
     */
	 private String email ;

    /**
     * 
     */
	 private String name ;

    /**
     * 
     */
	 private String culture ;

    /**
     * 
     */
	 private String currency ;

    /**
     * 
     */
	 private String country ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getTimezone() {
	 	return timezone;
	 }  
	 
	 public void setTimezone(String  timezone) {
	 	this.timezone = timezone;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getPhone() {
	 	return phone;
	 }  
	 
	 public void setPhone(String  phone) {
	 	this.phone = phone;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmail() {
	 	return email;
	 }  
	 
	 public void setEmail(String  email) {
	 	this.email = email;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCulture() {
	 	return culture;
	 }  
	 
	 public void setCulture(String  culture) {
	 	this.culture = culture;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrency() {
	 	return currency;
	 }  
	 
	 public void setCurrency(String  currency) {
	 	this.currency = currency;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCountry() {
	 	return country;
	 }  
	 
	 public void setCountry(String  country) {
	 	this.country = country;
	 }


}