/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SettingsSettingsInput extends Object {



    /**
     * site Subdomain
     */
	 private String siteSubdomain ;


    /**
     * setting Id
     */
	 private String settingId ;


    /**
     * setting Name
     */
	 private String settingName ;


    /**
     * setting Value
     */
	 private String settingValue ;


    /**
     * setting Description
     */
	 private String settingDescription ;



	/**
	 * site Subdomain
	 * 
	 * 
	 */
	 public String getSiteSubdomain() {
	 	return siteSubdomain;
	 }  
	 
	 public void setSiteSubdomain(String  siteSubdomain) {
	 	this.siteSubdomain = siteSubdomain;
	 }


	/**
	 * setting Id
	 * 
	 * 
	 */
	 public String getSettingId() {
	 	return settingId;
	 }  
	 
	 public void setSettingId(String  settingId) {
	 	this.settingId = settingId;
	 }


	/**
	 * setting Name
	 * 
	 * 
	 */
	 public String getSettingName() {
	 	return settingName;
	 }  
	 
	 public void setSettingName(String  settingName) {
	 	this.settingName = settingName;
	 }


	/**
	 * setting Value
	 * 
	 * 
	 */
	 public String getSettingValue() {
	 	return settingValue;
	 }  
	 
	 public void setSettingValue(String  settingValue) {
	 	this.settingValue = settingValue;
	 }


	/**
	 * setting Description
	 * 
	 * 
	 */
	 public String getSettingDescription() {
	 	return settingDescription;
	 }  
	 
	 public void setSettingDescription(String  settingDescription) {
	 	this.settingDescription = settingDescription;
	 }


}