/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class TestData extends Object {


    /**
     * 
     */
	 private List<ApplicationResponse> applicationResponseList ;

    /**
     * 
     */
	 private List<ApplicationPlan> applicationPlanList ;

    /**
     * 
     */
	 private List<ApplicationInCompanyResponse> applicationInCompanyResponseList ;

    /**
     * 
     */
	 private List<CompanyInfoRequest> companyInfoRequestList ;

    /**
     * 
     */
	 private List<CompanyInfoResponse> companyInfoResponseList ;

    /**
     * 
     */
	 private List<SetActiveMarketingPlanResponse> setActiveMarketingPlanResponseList ;

    /**
     * 
     */
	 private List<EventResponse> eventResponseList ;

    /**
     * 
     */
	 private List<EventParam> eventParamList ;

    /**
     * 
     */
	 private List<SettingRequest> settingRequestList ;

    /**
     * 
     */
	 private List<SettingResponse> settingResponseList ;

    /**
     * 
     */
	 private List<SiteResponse> siteResponseList ;

    /**
     * 
     */
	 private List<SiteRequest> siteRequestList ;

    /**
     * 
     */
	 private List<UserResponse> userResponseList ;

    /**
     * 
     */
	 private List<UserApiKeysResponse> userApiKeysResponseList ;

    /**
     * 
     */
	 private List<UserRequest> userRequestList ;


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ApplicationResponse> getApplicationResponseList() {
	 	return applicationResponseList;
	 }  
	 
	 public void setApplicationResponseList(List<ApplicationResponse>  applicationResponseList) {
	 	this.applicationResponseList = applicationResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<ApplicationPlan> getApplicationPlanList() {
	 	return applicationPlanList;
	 }  
	 
	 public void setApplicationPlanList(List<ApplicationPlan>  applicationPlanList) {
	 	this.applicationPlanList = applicationPlanList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<ApplicationInCompanyResponse> getApplicationInCompanyResponseList() {
	 	return applicationInCompanyResponseList;
	 }  
	 
	 public void setApplicationInCompanyResponseList(List<ApplicationInCompanyResponse>  applicationInCompanyResponseList) {
	 	this.applicationInCompanyResponseList = applicationInCompanyResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<CompanyInfoRequest> getCompanyInfoRequestList() {
	 	return companyInfoRequestList;
	 }  
	 
	 public void setCompanyInfoRequestList(List<CompanyInfoRequest>  companyInfoRequestList) {
	 	this.companyInfoRequestList = companyInfoRequestList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<CompanyInfoResponse> getCompanyInfoResponseList() {
	 	return companyInfoResponseList;
	 }  
	 
	 public void setCompanyInfoResponseList(List<CompanyInfoResponse>  companyInfoResponseList) {
	 	this.companyInfoResponseList = companyInfoResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SetActiveMarketingPlanResponse> getSetActiveMarketingPlanResponseList() {
	 	return setActiveMarketingPlanResponseList;
	 }  
	 
	 public void setSetActiveMarketingPlanResponseList(List<SetActiveMarketingPlanResponse>  setActiveMarketingPlanResponseList) {
	 	this.setActiveMarketingPlanResponseList = setActiveMarketingPlanResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<EventResponse> getEventResponseList() {
	 	return eventResponseList;
	 }  
	 
	 public void setEventResponseList(List<EventResponse>  eventResponseList) {
	 	this.eventResponseList = eventResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<EventParam> getEventParamList() {
	 	return eventParamList;
	 }  
	 
	 public void setEventParamList(List<EventParam>  eventParamList) {
	 	this.eventParamList = eventParamList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SettingRequest> getSettingRequestList() {
	 	return settingRequestList;
	 }  
	 
	 public void setSettingRequestList(List<SettingRequest>  settingRequestList) {
	 	this.settingRequestList = settingRequestList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SettingResponse> getSettingResponseList() {
	 	return settingResponseList;
	 }  
	 
	 public void setSettingResponseList(List<SettingResponse>  settingResponseList) {
	 	this.settingResponseList = settingResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SiteResponse> getSiteResponseList() {
	 	return siteResponseList;
	 }  
	 
	 public void setSiteResponseList(List<SiteResponse>  siteResponseList) {
	 	this.siteResponseList = siteResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SiteRequest> getSiteRequestList() {
	 	return siteRequestList;
	 }  
	 
	 public void setSiteRequestList(List<SiteRequest>  siteRequestList) {
	 	this.siteRequestList = siteRequestList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<UserResponse> getUserResponseList() {
	 	return userResponseList;
	 }  
	 
	 public void setUserResponseList(List<UserResponse>  userResponseList) {
	 	this.userResponseList = userResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<UserApiKeysResponse> getUserApiKeysResponseList() {
	 	return userApiKeysResponseList;
	 }  
	 
	 public void setUserApiKeysResponseList(List<UserApiKeysResponse>  userApiKeysResponseList) {
	 	this.userApiKeysResponseList = userApiKeysResponseList;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<UserRequest> getUserRequestList() {
	 	return userRequestList;
	 }  
	 
	 public void setUserRequestList(List<UserRequest>  userRequestList) {
	 	this.userRequestList = userRequestList;
	 }


}