/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class UserResponse extends Object {


    /**
     * 
     */
	 private String user_roles ;

    /**
     * 
     */
	 private String private_key ;

    /**
     * 
     */
	 private Boolean deleted ;

    /**
     * 
     */
	 private Boolean is_subscribed_to_newsletter ;

    /**
     * 
     */
	 private String currency ;

    /**
     * 
     */
	 private String country ;

    /**
     * 
     */
	 private Integer id ;

    /**
     * 
     */
	 private String first_name ;

    /**
     * 
     */
	 private String timezone ;

    /**
     * 
     */
	 private String googleapps_user_name ;

    /**
     * 
     */
	 private String email ;

    /**
     * 
     */
	 private Date registration_date ;

    /**
     * 
     */
	 private String last_name ;

    /**
     * 
     */
	 private Boolean active ;

    /**
     * 
     */
	 private String yahoo_user_name ;

    /**
     * 
     */
	 private String facebook_id ;

    /**
     * 
     */
	 private String public_key ;

    /**
     * 
     */
	 private String culture ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getUser_roles() {
	 	return user_roles;
	 }  
	 
	 public void setUser_roles(String  user_roles) {
	 	this.user_roles = user_roles;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getPrivate_key() {
	 	return private_key;
	 }  
	 
	 public void setPrivate_key(String  private_key) {
	 	this.private_key = private_key;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getDeleted() {
	 	return deleted;
	 }  
	 
	 public void setDeleted(Boolean  deleted) {
	 	this.deleted = deleted;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getIs_subscribed_to_newsletter() {
	 	return is_subscribed_to_newsletter;
	 }  
	 
	 public void setIs_subscribed_to_newsletter(Boolean  is_subscribed_to_newsletter) {
	 	this.is_subscribed_to_newsletter = is_subscribed_to_newsletter;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrency() {
	 	return currency;
	 }  
	 
	 public void setCurrency(String  currency) {
	 	this.currency = currency;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCountry() {
	 	return country;
	 }  
	 
	 public void setCountry(String  country) {
	 	this.country = country;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return id;
	 }  
	 
	 public void setId(Integer  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFirst_name() {
	 	return first_name;
	 }  
	 
	 public void setFirst_name(String  first_name) {
	 	this.first_name = first_name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getTimezone() {
	 	return timezone;
	 }  
	 
	 public void setTimezone(String  timezone) {
	 	this.timezone = timezone;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getGoogleapps_user_name() {
	 	return googleapps_user_name;
	 }  
	 
	 public void setGoogleapps_user_name(String  googleapps_user_name) {
	 	this.googleapps_user_name = googleapps_user_name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmail() {
	 	return email;
	 }  
	 
	 public void setEmail(String  email) {
	 	this.email = email;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getRegistration_date() {
	 	return registration_date;
	 }  
	 
	 public void setRegistration_date(Date  registration_date) {
	 	this.registration_date = registration_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getLast_name() {
	 	return last_name;
	 }  
	 
	 public void setLast_name(String  last_name) {
	 	this.last_name = last_name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getActive() {
	 	return active;
	 }  
	 
	 public void setActive(Boolean  active) {
	 	this.active = active;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getYahoo_user_name() {
	 	return yahoo_user_name;
	 }  
	 
	 public void setYahoo_user_name(String  yahoo_user_name) {
	 	this.yahoo_user_name = yahoo_user_name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFacebook_id() {
	 	return facebook_id;
	 }  
	 
	 public void setFacebook_id(String  facebook_id) {
	 	this.facebook_id = facebook_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getPublic_key() {
	 	return public_key;
	 }  
	 
	 public void setPublic_key(String  public_key) {
	 	this.public_key = public_key;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCulture() {
	 	return culture;
	 }  
	 
	 public void setCulture(String  culture) {
	 	this.culture = culture;
	 }


}