/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.platform.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class UserApiKeysResponse extends Object {



    /**
     * 
     */
	 private String private_key ;


    /**
     * 
     */
	 private String public_key ;



	/**
	 * 
	 * 
	 * 
	 */
	 public String getPrivate_key() {
	 	return private_key;
	 }  
	 
	 public void setPrivate_key(String  private_key) {
	 	this.private_key = private_key;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getPublic_key() {
	 	return public_key;
	 }  
	 
	 public void setPublic_key(String  public_key) {
	 	this.public_key = public_key;
	 }


}