/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class AddressRequest extends Object {


    /**
     * 
     */
	 private String fax_number ;

    /**
     * 
     */
	 private String first_name ;

    /**
     * 
     */
	 private String state_province ;

    /**
     * 
     */
	 private String phone_number ;

    /**
     * 
     */
	 private String email ;

    /**
     * 
     */
	 private String company ;

    /**
     * 
     */
	 private String last_name ;

    /**
     * 
     */
	 private String address1 ;

    /**
     * 
     */
	 private String address2 ;

    /**
     * 
     */
	 private String zip_postal_code ;

    /**
     * 
     */
	 private String country ;

    /**
     * 
     */
	 private String city ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getFax_number() {
	 	return fax_number;
	 }  
	 
	 public void setFax_number(String  fax_number) {
	 	this.fax_number = fax_number;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFirst_name() {
	 	return first_name;
	 }  
	 
	 public void setFirst_name(String  first_name) {
	 	this.first_name = first_name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getState_province() {
	 	return state_province;
	 }  
	 
	 public void setState_province(String  state_province) {
	 	this.state_province = state_province;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getPhone_number() {
	 	return phone_number;
	 }  
	 
	 public void setPhone_number(String  phone_number) {
	 	this.phone_number = phone_number;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmail() {
	 	return email;
	 }  
	 
	 public void setEmail(String  email) {
	 	this.email = email;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCompany() {
	 	return company;
	 }  
	 
	 public void setCompany(String  company) {
	 	this.company = company;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getLast_name() {
	 	return last_name;
	 }  
	 
	 public void setLast_name(String  last_name) {
	 	this.last_name = last_name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getAddress1() {
	 	return address1;
	 }  
	 
	 public void setAddress1(String  address1) {
	 	this.address1 = address1;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getAddress2() {
	 	return address2;
	 }  
	 
	 public void setAddress2(String  address2) {
	 	this.address2 = address2;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getZip_postal_code() {
	 	return zip_postal_code;
	 }  
	 
	 public void setZip_postal_code(String  zip_postal_code) {
	 	this.zip_postal_code = zip_postal_code;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCountry() {
	 	return country;
	 }  
	 
	 public void setCountry(String  country) {
	 	this.country = country;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCity() {
	 	return city;
	 }  
	 
	 public void setCity(String  city) {
	 	this.city = city;
	 }


}