/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class Address extends Object {



    /**
     * 
     */
	 private java.util.Date UpdatedOn ;


    /**
     * 
     */
	 private String PhoneNumber ;


    /**
     * 
     */
	 private Integer StateProvinceId ;


    /**
     * 
     */
	 private String LastName ;


    /**
     * 
     */
	 private String City ;


    /**
     * 
     */
	 private String Email ;


    /**
     * 
     */
	 private Integer CustomerId ;


    /**
     * 
     */
	 private String Address2 ;


    /**
     * 
     */
	 private String FaxNumber ;


    /**
     * 
     */
	 private String Address1 ;


    /**
     * 
     */
	 private java.util.Date CreatedOn ;


    /**
     * 
     */
	 private Integer CountryId ;


    /**
     * 
     */
	 private Boolean IsBillingAddress ;


    /**
     * 
     */
	 private String FirstName ;


    /**
     * 
     */
	 private Integer Id ;


    /**
     * 
     */
	 private String Company ;


    /**
     * 
     */
	 private String ZipPostalCode ;



	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getUpdatedOn() {
	 	return UpdatedOn;
	 }  
	 
	 public void setUpdatedOn(java.util.Date  UpdatedOn) {
	 	this.UpdatedOn = UpdatedOn;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getPhoneNumber() {
	 	return PhoneNumber;
	 }  
	 
	 public void setPhoneNumber(String  PhoneNumber) {
	 	this.PhoneNumber = PhoneNumber;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getStateProvinceId() {
	 	return StateProvinceId;
	 }  
	 
	 public void setStateProvinceId(Integer  StateProvinceId) {
	 	this.StateProvinceId = StateProvinceId;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getLastName() {
	 	return LastName;
	 }  
	 
	 public void setLastName(String  LastName) {
	 	this.LastName = LastName;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCity() {
	 	return City;
	 }  
	 
	 public void setCity(String  City) {
	 	this.City = City;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmail() {
	 	return Email;
	 }  
	 
	 public void setEmail(String  Email) {
	 	this.Email = Email;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getCustomerId() {
	 	return CustomerId;
	 }  
	 
	 public void setCustomerId(Integer  CustomerId) {
	 	this.CustomerId = CustomerId;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getAddress2() {
	 	return Address2;
	 }  
	 
	 public void setAddress2(String  Address2) {
	 	this.Address2 = Address2;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getFaxNumber() {
	 	return FaxNumber;
	 }  
	 
	 public void setFaxNumber(String  FaxNumber) {
	 	this.FaxNumber = FaxNumber;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getAddress1() {
	 	return Address1;
	 }  
	 
	 public void setAddress1(String  Address1) {
	 	this.Address1 = Address1;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getCreatedOn() {
	 	return CreatedOn;
	 }  
	 
	 public void setCreatedOn(java.util.Date  CreatedOn) {
	 	this.CreatedOn = CreatedOn;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getCountryId() {
	 	return CountryId;
	 }  
	 
	 public void setCountryId(Integer  CountryId) {
	 	this.CountryId = CountryId;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getIsBillingAddress() {
	 	return IsBillingAddress;
	 }  
	 
	 public void setIsBillingAddress(Boolean  IsBillingAddress) {
	 	this.IsBillingAddress = IsBillingAddress;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getFirstName() {
	 	return FirstName;
	 }  
	 
	 public void setFirstName(String  FirstName) {
	 	this.FirstName = FirstName;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return Id;
	 }  
	 
	 public void setId(Integer  Id) {
	 	this.Id = Id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCompany() {
	 	return Company;
	 }  
	 
	 public void setCompany(String  Company) {
	 	this.Company = Company;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getZipPostalCode() {
	 	return ZipPostalCode;
	 }  
	 
	 public void setZipPostalCode(String  ZipPostalCode) {
	 	this.ZipPostalCode = ZipPostalCode;
	 }


}