/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class Country extends Object {


    /**
     * 
     */
	 private Integer NumericIsoCode ;

    /**
     * 
     */
	 private String Fips ;

    /**
     * 
     */
	 private Integer DisplayOrder ;

    /**
     * 
     */
	 private String Tld ;

    /**
     * 
     */
	 private Integer Area ;

    /**
     * 
     */
	 private String Capital ;

    /**
     * 
     */
	 private Integer Geonameid ;

    /**
     * 
     */
	 private String PostalCodeRegex ;

    /**
     * 
     */
	 private String EquivalentFipsCode ;

    /**
     * 
     */
	 private String CurrencyCode ;

    /**
     * 
     */
	 private String Languages ;

    /**
     * 
     */
	 private String Name ;

    /**
     * 
     */
	 private String ThreeLetterIsoCode ;

    /**
     * 
     */
	 private String CurrencyName ;

    /**
     * 
     */
	 private String PostalCodeFormat ;

    /**
     * 
     */
	 private String Neighbours ;

    /**
     * 
     */
	 private Integer Population ;

    /**
     * 
     */
	 private Integer Id ;

    /**
     * 
     */
	 private String Continent ;

    /**
     * 
     */
	 private String TwoLetterIsoCode ;


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getNumericIsoCode() {
	 	return NumericIsoCode;
	 }  
	 
	 public void setNumericIsoCode(Integer  NumericIsoCode) {
	 	this.NumericIsoCode = NumericIsoCode;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFips() {
	 	return Fips;
	 }  
	 
	 public void setFips(String  Fips) {
	 	this.Fips = Fips;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getDisplayOrder() {
	 	return DisplayOrder;
	 }  
	 
	 public void setDisplayOrder(Integer  DisplayOrder) {
	 	this.DisplayOrder = DisplayOrder;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getTld() {
	 	return Tld;
	 }  
	 
	 public void setTld(String  Tld) {
	 	this.Tld = Tld;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getArea() {
	 	return Area;
	 }  
	 
	 public void setArea(Integer  Area) {
	 	this.Area = Area;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCapital() {
	 	return Capital;
	 }  
	 
	 public void setCapital(String  Capital) {
	 	this.Capital = Capital;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getGeonameid() {
	 	return Geonameid;
	 }  
	 
	 public void setGeonameid(Integer  Geonameid) {
	 	this.Geonameid = Geonameid;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getPostalCodeRegex() {
	 	return PostalCodeRegex;
	 }  
	 
	 public void setPostalCodeRegex(String  PostalCodeRegex) {
	 	this.PostalCodeRegex = PostalCodeRegex;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getEquivalentFipsCode() {
	 	return EquivalentFipsCode;
	 }  
	 
	 public void setEquivalentFipsCode(String  EquivalentFipsCode) {
	 	this.EquivalentFipsCode = EquivalentFipsCode;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrencyCode() {
	 	return CurrencyCode;
	 }  
	 
	 public void setCurrencyCode(String  CurrencyCode) {
	 	this.CurrencyCode = CurrencyCode;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getLanguages() {
	 	return Languages;
	 }  
	 
	 public void setLanguages(String  Languages) {
	 	this.Languages = Languages;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return Name;
	 }  
	 
	 public void setName(String  Name) {
	 	this.Name = Name;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getThreeLetterIsoCode() {
	 	return ThreeLetterIsoCode;
	 }  
	 
	 public void setThreeLetterIsoCode(String  ThreeLetterIsoCode) {
	 	this.ThreeLetterIsoCode = ThreeLetterIsoCode;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrencyName() {
	 	return CurrencyName;
	 }  
	 
	 public void setCurrencyName(String  CurrencyName) {
	 	this.CurrencyName = CurrencyName;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getPostalCodeFormat() {
	 	return PostalCodeFormat;
	 }  
	 
	 public void setPostalCodeFormat(String  PostalCodeFormat) {
	 	this.PostalCodeFormat = PostalCodeFormat;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getNeighbours() {
	 	return Neighbours;
	 }  
	 
	 public void setNeighbours(String  Neighbours) {
	 	this.Neighbours = Neighbours;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getPopulation() {
	 	return Population;
	 }  
	 
	 public void setPopulation(Integer  Population) {
	 	this.Population = Population;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return Id;
	 }  
	 
	 public void setId(Integer  Id) {
	 	this.Id = Id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getContinent() {
	 	return Continent;
	 }  
	 
	 public void setContinent(String  Continent) {
	 	this.Continent = Continent;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getTwoLetterIsoCode() {
	 	return TwoLetterIsoCode;
	 }  
	 
	 public void setTwoLetterIsoCode(String  TwoLetterIsoCode) {
	 	this.TwoLetterIsoCode = TwoLetterIsoCode;
	 }


}