/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class CreditCardRequest extends Object {


    /**
     * 
     */
	 private String card_number ;

    /**
     * 
     */
	 private Date expiration_date ;

    /**
     * 
     */
	 private String cvv ;

    /**
     * 
     */
	 private String last_name_on_card ;

    /**
     * 
     */
	 private String first_name_on_card ;


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCard_number() {
	 	return card_number;
	 }  
	 
	 public void setCard_number(String  card_number) {
	 	this.card_number = card_number;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getExpiration_date() {
	 	return expiration_date;
	 }  
	 
	 public void setExpiration_date(Date  expiration_date) {
	 	this.expiration_date = expiration_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCvv() {
	 	return cvv;
	 }  
	 
	 public void setCvv(String  cvv) {
	 	this.cvv = cvv;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getLast_name_on_card() {
	 	return last_name_on_card;
	 }  
	 
	 public void setLast_name_on_card(String  last_name_on_card) {
	 	this.last_name_on_card = last_name_on_card;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getFirst_name_on_card() {
	 	return first_name_on_card;
	 }  
	 
	 public void setFirst_name_on_card(String  first_name_on_card) {
	 	this.first_name_on_card = first_name_on_card;
	 }


}