/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class ProductsRevenues extends Object {



    /**
     * 
     */
	 private String product ;


    /**
     * 
     */
	 private Integer product_id ;


    /**
     * 
     */
	 private Double revenues ;


    /**
     * 
     */
	 private java.util.Date date ;


    /**
     * 
     */
	 private String currency_code ;



	/**
	 * 
	 * 
	 * 
	 */
	 public String getProduct() {
	 	return product;
	 }  
	 
	 public void setProduct(String  product) {
	 	this.product = product;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getProduct_id() {
	 	return product_id;
	 }  
	 
	 public void setProduct_id(Integer  product_id) {
	 	this.product_id = product_id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getRevenues() {
	 	return revenues;
	 }  
	 
	 public void setRevenues(Double  revenues) {
	 	this.revenues = revenues;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getDate() {
	 	return date;
	 }  
	 
	 public void setDate(java.util.Date  date) {
	 	this.date = date;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrency_code() {
	 	return currency_code;
	 }  
	 
	 public void setCurrency_code(String  currency_code) {
	 	this.currency_code = currency_code;
	 }


}