/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.List;

import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class ProductRequest extends Object {



    /**
     * 
     */
	 private Integer id ;


    /**
     * 
     */
	 private String is_billing_address_at_signup_required ;


    /**
     * 
     */
	 private String is_credit_card_at_signup_required ;


    /**
     * 
     */
	 private List<PricingPlanRequest> pricing_plans  =  new ArrayList<PricingPlanRequest>();


    /**
     * 
     */
	 private String description ;


    /**
     * 
     */
	 private String accounting_code ;


    /**
     * 
     */
	 private String api_reference1 ;


    /**
     * 
     */
	 private String name ;


    /**
     * 
     */
	 private Integer product_family_id ;



	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return id;
	 }  
	 
	 public void setId(Integer  id) {
	 	this.id = id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getIs_billing_address_at_signup_required() {
	 	return is_billing_address_at_signup_required;
	 }  
	 
	 public void setIs_billing_address_at_signup_required(String  is_billing_address_at_signup_required) {
	 	this.is_billing_address_at_signup_required = is_billing_address_at_signup_required;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getIs_credit_card_at_signup_required() {
	 	return is_credit_card_at_signup_required;
	 }  
	 
	 public void setIs_credit_card_at_signup_required(String  is_credit_card_at_signup_required) {
	 	this.is_credit_card_at_signup_required = is_credit_card_at_signup_required;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<PricingPlanRequest> getPricing_plans() {
	 	return pricing_plans;
	 }  
	 
	 public void setPricing_plans(List<PricingPlanRequest>  pricing_plans) {
	 	this.pricing_plans = pricing_plans;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getDescription() {
	 	return description;
	 }  
	 
	 public void setDescription(String  description) {
	 	this.description = description;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getAccounting_code() {
	 	return accounting_code;
	 }  
	 
	 public void setAccounting_code(String  accounting_code) {
	 	this.accounting_code = accounting_code;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getApi_reference1() {
	 	return api_reference1;
	 }  
	 
	 public void setApi_reference1(String  api_reference1) {
	 	this.api_reference1 = api_reference1;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getName() {
	 	return name;
	 }  
	 
	 public void setName(String  name) {
	 	this.name = name;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getProduct_family_id() {
	 	return product_family_id;
	 }  
	 
	 public void setProduct_family_id(Integer  product_family_id) {
	 	this.product_family_id = product_family_id;
	 }


}