/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class RevenueAmount extends Object {



    /**
     * 
     */
	 private Double amount ;


    /**
     * 
     */
	 private String currency_code ;



	/**
	 * 
	 * 
	 * 
	 */
	 public Double getAmount() {
	 	return amount;
	 }  
	 
	 public void setAmount(Double  amount) {
	 	this.amount = amount;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCurrency_code() {
	 	return currency_code;
	 }  
	 
	 public void setCurrency_code(String  currency_code) {
	 	this.currency_code = currency_code;
	 }


}