/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.Date;

import java.util.List;

import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class Statement extends Object {



    /**
     * 
     */
	 private Integer subscription_id ;


    /**
     * 
     */
	 private String status ;


    /**
     * 
     */
	 private java.util.Date statement_date ;


    /**
     * 
     */
	 private Double current_charges ;


    /**
     * 
     */
	 private String customer_first_name ;


    /**
     * 
     */
	 private Integer billing_address_id ;


    /**
     * 
     */
	 private Integer id ;


    /**
     * 
     */
	 private List<StatementDetail> statement_details  =  new ArrayList<StatementDetail>();


    /**
     * 
     */
	 private String customer_last_name ;


    /**
     * 
     */
	 private Double starting_balance ;


    /**
     * 
     */
	 private Double payments_and_credits ;


    /**
     * 
     */
	 private String email ;


    /**
     * 
     */
	 private java.util.Date billing_start_date ;


    /**
     * 
     */
	 private java.util.Date billing_end_date ;



	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getSubscription_id() {
	 	return subscription_id;
	 }  
	 
	 public void setSubscription_id(Integer  subscription_id) {
	 	this.subscription_id = subscription_id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getStatus() {
	 	return status;
	 }  
	 
	 public void setStatus(String  status) {
	 	this.status = status;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getStatement_date() {
	 	return statement_date;
	 }  
	 
	 public void setStatement_date(java.util.Date  statement_date) {
	 	this.statement_date = statement_date;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getCurrent_charges() {
	 	return current_charges;
	 }  
	 
	 public void setCurrent_charges(Double  current_charges) {
	 	this.current_charges = current_charges;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCustomer_first_name() {
	 	return customer_first_name;
	 }  
	 
	 public void setCustomer_first_name(String  customer_first_name) {
	 	this.customer_first_name = customer_first_name;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getBilling_address_id() {
	 	return billing_address_id;
	 }  
	 
	 public void setBilling_address_id(Integer  billing_address_id) {
	 	this.billing_address_id = billing_address_id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return id;
	 }  
	 
	 public void setId(Integer  id) {
	 	this.id = id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<StatementDetail> getStatement_details() {
	 	return statement_details;
	 }  
	 
	 public void setStatement_details(List<StatementDetail>  statement_details) {
	 	this.statement_details = statement_details;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getCustomer_last_name() {
	 	return customer_last_name;
	 }  
	 
	 public void setCustomer_last_name(String  customer_last_name) {
	 	this.customer_last_name = customer_last_name;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getStarting_balance() {
	 	return starting_balance;
	 }  
	 
	 public void setStarting_balance(Double  starting_balance) {
	 	this.starting_balance = starting_balance;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getPayments_and_credits() {
	 	return payments_and_credits;
	 }  
	 
	 public void setPayments_and_credits(Double  payments_and_credits) {
	 	this.payments_and_credits = payments_and_credits;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getEmail() {
	 	return email;
	 }  
	 
	 public void setEmail(String  email) {
	 	this.email = email;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getBilling_start_date() {
	 	return billing_start_date;
	 }  
	 
	 public void setBilling_start_date(java.util.Date  billing_start_date) {
	 	this.billing_start_date = billing_start_date;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getBilling_end_date() {
	 	return billing_end_date;
	 }  
	 
	 public void setBilling_end_date(java.util.Date  billing_end_date) {
	 	this.billing_end_date = billing_end_date;
	 }


}