/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.Date;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class StatementDetail extends Object {



    /**
     * 
     */
	 private Double amount ;


    /**
     * 
     */
	 private Integer id ;


    /**
     * 
     */
	 private Integer currency_id ;


    /**
     * 
     */
	 private String details ;


    /**
     * 
     */
	 private String type ;


    /**
     * 
     */
	 private java.util.Date date ;


    /**
     * 
     */
	 private Integer statement_id ;



	/**
	 * 
	 * 
	 * 
	 */
	 public Double getAmount() {
	 	return amount;
	 }  
	 
	 public void setAmount(Double  amount) {
	 	this.amount = amount;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return id;
	 }  
	 
	 public void setId(Integer  id) {
	 	this.id = id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getCurrency_id() {
	 	return currency_id;
	 }  
	 
	 public void setCurrency_id(Integer  currency_id) {
	 	this.currency_id = currency_id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getDetails() {
	 	return details;
	 }  
	 
	 public void setDetails(String  details) {
	 	this.details = details;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public String getType() {
	 	return type;
	 }  
	 
	 public void setType(String  type) {
	 	this.type = type;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public java.util.Date getDate() {
	 	return date;
	 }  
	 
	 public void setDate(java.util.Date  date) {
	 	this.date = date;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getStatement_id() {
	 	return statement_id;
	 }  
	 
	 public void setStatement_id(Integer  statement_id) {
	 	this.statement_id = statement_id;
	 }


}