/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.List;

import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SubscriptionItemResponse extends Object {



    /**
     * 
     */
	 private Integer subscription_id ;


    /**
     * 
     */
	 private Integer product_item_id ;


    /**
     * 
     */
	 private Double quantity ;


    /**
     * 
     */
	 private List<SubscriptionItemHistoryResponse> update_history  =  new ArrayList<SubscriptionItemHistoryResponse>();



	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getSubscription_id() {
	 	return subscription_id;
	 }  
	 
	 public void setSubscription_id(Integer  subscription_id) {
	 	this.subscription_id = subscription_id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getProduct_item_id() {
	 	return product_item_id;
	 }  
	 
	 public void setProduct_item_id(Integer  product_item_id) {
	 	this.product_item_id = product_item_id;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public Double getQuantity() {
	 	return quantity;
	 }  
	 
	 public void setQuantity(Double  quantity) {
	 	this.quantity = quantity;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionItemHistoryResponse> getUpdate_history() {
	 	return update_history;
	 }  
	 
	 public void setUpdate_history(List<SubscriptionItemHistoryResponse>  update_history) {
	 	this.update_history = update_history;
	 }


}