/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class SubscriptionResponse extends Object {


    /**
     * 
     */
	 private Date signup_date ;

    /**
     * 
     */
	 private Integer product_id ;

    /**
     * 
     */
	 private ServiceResult service_result ;

    /**
     * 
     */
	 private ProductResponse next_product ;

    /**
     * 
     */
	 private CustomerResponse customer ;

    /**
     * 
     */
	 private Date next_assesment ;

    /**
     * 
     */
	 private String cancellation_details ;

    /**
     * 
     */
	 private Integer billing_address_id ;

    /**
     * 
     */
	 private Currency currency ;

    /**
     * 
     */
	 private PricingPlanResponse product_pricing_plan ;

    /**
     * 
     */
	 private Integer id ;

    /**
     * 
     */
	 private Date end_date ;

    /**
     * 
     */
	 private CreditCardResponse credit_card ;

    /**
     * 
     */
	 private Double current_ballance ;

    /**
     * 
     */
	 private Double revenue ;

    /**
     * 
     */
	 private List<SubscriptionItemResponse> subscription_items  =  new ArrayList<SubscriptionItemResponse>();

    /**
     * 
     */
	 private String status ;

    /**
     * 
     */
	 private Boolean is_cancelled_at_end_of_period ;

    /**
     * 
     */
	 private PricingPlanResponse next_product_pricing_plan ;

    /**
     * 
     */
	 private Date cancellation_date ;

    /**
     * 
     */
	 private ProductResponse product ;

    /**
     * 
     */
	 private Integer credit_card_id ;

    /**
     * 
     */
	 private Boolean is_trial ;

    /**
     * 
     */
	 private Integer pricing_plan_id ;

    /**
     * 
     */
	 private Date start_date ;

    /**
     * 
     */
	 private Integer customer_id ;

    /**
     * 
     */
	 private AddressResponse billing_address ;


	/**
	 * 
	 * 
	 * 
	 */
	 public Date getSignup_date() {
	 	return signup_date;
	 }  
	 
	 public void setSignup_date(Date  signup_date) {
	 	this.signup_date = signup_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getProduct_id() {
	 	return product_id;
	 }  
	 
	 public void setProduct_id(Integer  product_id) {
	 	this.product_id = product_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public ServiceResult getService_result() {
	 	return service_result;
	 }  
	 
	 public void setService_result(ServiceResult  service_result) {
	 	this.service_result = service_result;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public ProductResponse getNext_product() {
	 	return next_product;
	 }  
	 
	 public void setNext_product(ProductResponse  next_product) {
	 	this.next_product = next_product;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public CustomerResponse getCustomer() {
	 	return customer;
	 }  
	 
	 public void setCustomer(CustomerResponse  customer) {
	 	this.customer = customer;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getNext_assesment() {
	 	return next_assesment;
	 }  
	 
	 public void setNext_assesment(Date  next_assesment) {
	 	this.next_assesment = next_assesment;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getCancellation_details() {
	 	return cancellation_details;
	 }  
	 
	 public void setCancellation_details(String  cancellation_details) {
	 	this.cancellation_details = cancellation_details;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getBilling_address_id() {
	 	return billing_address_id;
	 }  
	 
	 public void setBilling_address_id(Integer  billing_address_id) {
	 	this.billing_address_id = billing_address_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Currency getCurrency() {
	 	return currency;
	 }  
	 
	 public void setCurrency(Currency  currency) {
	 	this.currency = currency;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public PricingPlanResponse getProduct_pricing_plan() {
	 	return product_pricing_plan;
	 }  
	 
	 public void setProduct_pricing_plan(PricingPlanResponse  product_pricing_plan) {
	 	this.product_pricing_plan = product_pricing_plan;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getId() {
	 	return id;
	 }  
	 
	 public void setId(Integer  id) {
	 	this.id = id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getEnd_date() {
	 	return end_date;
	 }  
	 
	 public void setEnd_date(Date  end_date) {
	 	this.end_date = end_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public CreditCardResponse getCredit_card() {
	 	return credit_card;
	 }  
	 
	 public void setCredit_card(CreditCardResponse  credit_card) {
	 	this.credit_card = credit_card;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getCurrent_ballance() {
	 	return current_ballance;
	 }  
	 
	 public void setCurrent_ballance(Double  current_ballance) {
	 	this.current_ballance = current_ballance;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Double getRevenue() {
	 	return revenue;
	 }  
	 
	 public void setRevenue(Double  revenue) {
	 	this.revenue = revenue;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionItemResponse> getSubscription_items() {
	 	return subscription_items;
	 }  
	 
	 public void setSubscription_items(List<SubscriptionItemResponse>  subscription_items) {
	 	this.subscription_items = subscription_items;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public String getStatus() {
	 	return status;
	 }  
	 
	 public void setStatus(String  status) {
	 	this.status = status;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getIs_cancelled_at_end_of_period() {
	 	return is_cancelled_at_end_of_period;
	 }  
	 
	 public void setIs_cancelled_at_end_of_period(Boolean  is_cancelled_at_end_of_period) {
	 	this.is_cancelled_at_end_of_period = is_cancelled_at_end_of_period;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public PricingPlanResponse getNext_product_pricing_plan() {
	 	return next_product_pricing_plan;
	 }  
	 
	 public void setNext_product_pricing_plan(PricingPlanResponse  next_product_pricing_plan) {
	 	this.next_product_pricing_plan = next_product_pricing_plan;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getCancellation_date() {
	 	return cancellation_date;
	 }  
	 
	 public void setCancellation_date(Date  cancellation_date) {
	 	this.cancellation_date = cancellation_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public ProductResponse getProduct() {
	 	return product;
	 }  
	 
	 public void setProduct(ProductResponse  product) {
	 	this.product = product;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getCredit_card_id() {
	 	return credit_card_id;
	 }  
	 
	 public void setCredit_card_id(Integer  credit_card_id) {
	 	this.credit_card_id = credit_card_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Boolean getIs_trial() {
	 	return is_trial;
	 }  
	 
	 public void setIs_trial(Boolean  is_trial) {
	 	this.is_trial = is_trial;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getPricing_plan_id() {
	 	return pricing_plan_id;
	 }  
	 
	 public void setPricing_plan_id(Integer  pricing_plan_id) {
	 	this.pricing_plan_id = pricing_plan_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Date getStart_date() {
	 	return start_date;
	 }  
	 
	 public void setStart_date(Date  start_date) {
	 	this.start_date = start_date;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public Integer getCustomer_id() {
	 	return customer_id;
	 }  
	 
	 public void setCustomer_id(Integer  customer_id) {
	 	this.customer_id = customer_id;
	 }

	/**
	 * 
	 * 
	 * 
	 */
	 public AddressResponse getBilling_address() {
	 	return billing_address;
	 }  
	 
	 public void setBilling_address(AddressResponse  billing_address) {
	 	this.billing_address = billing_address;
	 }


}