/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.dynabic.sdk.java.model;

import com.wordnik.swagger.runtime.annotations.*;
import java.util.List;


import java.util.List;

import java.util.ArrayList;


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author ramesh
 *
 */
public class TestData extends Object {



    /**
     * 
     */
	 private List<Address> addressList ;


    /**
     * 
     */
	 private List<StateProvince> stateProvinceList ;


    /**
     * 
     */
	 private List<Country> countryList ;


    /**
     * 
     */
	 private List<AddressRequest> addressRequestList ;


    /**
     * 
     */
	 private List<CustomerResponse> customerResponseList ;


    /**
     * 
     */
	 private List<CreditCardResponse> creditCardResponseList ;


    /**
     * 
     */
	 private List<CustomerRequest> customerRequestList ;


    /**
     * 
     */
	 private List<CreditCardRequest> creditCardRequestList ;


    /**
     * 
     */
	 private List<AddressResponse> addressResponseList ;


    /**
     * 
     */
	 private List<ProductResponse> productResponseList ;


    /**
     * 
     */
	 private List<PricingPlanResponse> pricingPlanResponseList ;


    /**
     * 
     */
	 private List<ProductFamilyResponse> productFamilyResponseList ;


    /**
     * 
     */
	 private List<ProductItemRequest> productItemRequestList ;


    /**
     * 
     */
	 private List<ProductPricingPlanPaymentScheduleRequest> productPricingPlanPaymentScheduleRequestList ;


    /**
     * 
     */
	 private List<ProductItemResponse> productItemResponseList ;


    /**
     * 
     */
	 private List<ProductMeteredPriceRequest> productMeteredPriceRequestList ;


    /**
     * 
     */
	 private List<ProductRequest> productRequestList ;


    /**
     * 
     */
	 private List<ProductFamilyRequest> productFamilyRequestList ;


    /**
     * 
     */
	 private List<ProductMeteredPriceResponse> productMeteredPriceResponseList ;


    /**
     * 
     */
	 private List<PricingPlanRequest> pricingPlanRequestList ;


    /**
     * 
     */
	 private List<ProductPricingPlanPaymentScheduleResponse> productPricingPlanPaymentScheduleResponseList ;


    /**
     * 
     */
	 private List<SiteSummary> siteSummaryList ;


    /**
     * 
     */
	 private List<ReportIntValueItem> reportIntValueItemList ;


    /**
     * 
     */
	 private List<ActiveSubscriptionsCountResponse> activeSubscriptionsCountResponseList ;


    /**
     * 
     */
	 private List<TotalSubscribersCountResponse> totalSubscribersCountResponseList ;


    /**
     * 
     */
	 private List<RevenueAmount> revenueAmountList ;


    /**
     * 
     */
	 private List<ProductsSignups> productsSignupsList ;


    /**
     * 
     */
	 private List<ProductsRevenues> productsRevenuesList ;


    /**
     * 
     */
	 private List<ReportDecimalValueItem> reportDecimalValueItemList ;


    /**
     * 
     */
	 private List<TodayNewSubscribersCountResponse> todayNewSubscribersCountResponseList ;


    /**
     * 
     */
	 private List<Statement> statementList ;


    /**
     * 
     */
	 private List<StatementDetail> statementDetailList ;


    /**
     * 
     */
	 private List<SubscriptionRequest> subscriptionRequestList ;


    /**
     * 
     */
	 private List<SubscriptionResponse> subscriptionResponseList ;


    /**
     * 
     */
	 private List<ServiceResult> serviceResultList ;


    /**
     * 
     */
	 private List<Currency> currencyList ;


    /**
     * 
     */
	 private List<CancellationRequest> cancellationRequestList ;


    /**
     * 
     */
	 private List<SubscriptionItemHistoryResponse> subscriptionItemHistoryResponseList ;


    /**
     * 
     */
	 private List<SubscriptionItemResponse> subscriptionItemResponseList ;


    /**
     * 
     */
	 private List<TransactionResponse> transactionResponseList ;


    /**
     * 
     */
	 private List<SubscriptionItemRequest> subscriptionItemRequestList ;


    /**
     * 
     */
	 private List<ChargeRequest> chargeRequestList ;


    /**
     * 
     */
	 private List<EventData> eventDataList ;



	/**
	 * 
	 * 
	 * 
	 */
	 public List<Address> getAddressList() {
	 	return addressList;
	 }  
	 
	 public void setAddressList(List<Address>  addressList) {
	 	this.addressList = addressList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<StateProvince> getStateProvinceList() {
	 	return stateProvinceList;
	 }  
	 
	 public void setStateProvinceList(List<StateProvince>  stateProvinceList) {
	 	this.stateProvinceList = stateProvinceList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<Country> getCountryList() {
	 	return countryList;
	 }  
	 
	 public void setCountryList(List<Country>  countryList) {
	 	this.countryList = countryList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<AddressRequest> getAddressRequestList() {
	 	return addressRequestList;
	 }  
	 
	 public void setAddressRequestList(List<AddressRequest>  addressRequestList) {
	 	this.addressRequestList = addressRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<CustomerResponse> getCustomerResponseList() {
	 	return customerResponseList;
	 }  
	 
	 public void setCustomerResponseList(List<CustomerResponse>  customerResponseList) {
	 	this.customerResponseList = customerResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<CreditCardResponse> getCreditCardResponseList() {
	 	return creditCardResponseList;
	 }  
	 
	 public void setCreditCardResponseList(List<CreditCardResponse>  creditCardResponseList) {
	 	this.creditCardResponseList = creditCardResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<CustomerRequest> getCustomerRequestList() {
	 	return customerRequestList;
	 }  
	 
	 public void setCustomerRequestList(List<CustomerRequest>  customerRequestList) {
	 	this.customerRequestList = customerRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<CreditCardRequest> getCreditCardRequestList() {
	 	return creditCardRequestList;
	 }  
	 
	 public void setCreditCardRequestList(List<CreditCardRequest>  creditCardRequestList) {
	 	this.creditCardRequestList = creditCardRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<AddressResponse> getAddressResponseList() {
	 	return addressResponseList;
	 }  
	 
	 public void setAddressResponseList(List<AddressResponse>  addressResponseList) {
	 	this.addressResponseList = addressResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductResponse> getProductResponseList() {
	 	return productResponseList;
	 }  
	 
	 public void setProductResponseList(List<ProductResponse>  productResponseList) {
	 	this.productResponseList = productResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<PricingPlanResponse> getPricingPlanResponseList() {
	 	return pricingPlanResponseList;
	 }  
	 
	 public void setPricingPlanResponseList(List<PricingPlanResponse>  pricingPlanResponseList) {
	 	this.pricingPlanResponseList = pricingPlanResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductFamilyResponse> getProductFamilyResponseList() {
	 	return productFamilyResponseList;
	 }  
	 
	 public void setProductFamilyResponseList(List<ProductFamilyResponse>  productFamilyResponseList) {
	 	this.productFamilyResponseList = productFamilyResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductItemRequest> getProductItemRequestList() {
	 	return productItemRequestList;
	 }  
	 
	 public void setProductItemRequestList(List<ProductItemRequest>  productItemRequestList) {
	 	this.productItemRequestList = productItemRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductPricingPlanPaymentScheduleRequest> getProductPricingPlanPaymentScheduleRequestList() {
	 	return productPricingPlanPaymentScheduleRequestList;
	 }  
	 
	 public void setProductPricingPlanPaymentScheduleRequestList(List<ProductPricingPlanPaymentScheduleRequest>  productPricingPlanPaymentScheduleRequestList) {
	 	this.productPricingPlanPaymentScheduleRequestList = productPricingPlanPaymentScheduleRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductItemResponse> getProductItemResponseList() {
	 	return productItemResponseList;
	 }  
	 
	 public void setProductItemResponseList(List<ProductItemResponse>  productItemResponseList) {
	 	this.productItemResponseList = productItemResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductMeteredPriceRequest> getProductMeteredPriceRequestList() {
	 	return productMeteredPriceRequestList;
	 }  
	 
	 public void setProductMeteredPriceRequestList(List<ProductMeteredPriceRequest>  productMeteredPriceRequestList) {
	 	this.productMeteredPriceRequestList = productMeteredPriceRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductRequest> getProductRequestList() {
	 	return productRequestList;
	 }  
	 
	 public void setProductRequestList(List<ProductRequest>  productRequestList) {
	 	this.productRequestList = productRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductFamilyRequest> getProductFamilyRequestList() {
	 	return productFamilyRequestList;
	 }  
	 
	 public void setProductFamilyRequestList(List<ProductFamilyRequest>  productFamilyRequestList) {
	 	this.productFamilyRequestList = productFamilyRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductMeteredPriceResponse> getProductMeteredPriceResponseList() {
	 	return productMeteredPriceResponseList;
	 }  
	 
	 public void setProductMeteredPriceResponseList(List<ProductMeteredPriceResponse>  productMeteredPriceResponseList) {
	 	this.productMeteredPriceResponseList = productMeteredPriceResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<PricingPlanRequest> getPricingPlanRequestList() {
	 	return pricingPlanRequestList;
	 }  
	 
	 public void setPricingPlanRequestList(List<PricingPlanRequest>  pricingPlanRequestList) {
	 	this.pricingPlanRequestList = pricingPlanRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductPricingPlanPaymentScheduleResponse> getProductPricingPlanPaymentScheduleResponseList() {
	 	return productPricingPlanPaymentScheduleResponseList;
	 }  
	 
	 public void setProductPricingPlanPaymentScheduleResponseList(List<ProductPricingPlanPaymentScheduleResponse>  productPricingPlanPaymentScheduleResponseList) {
	 	this.productPricingPlanPaymentScheduleResponseList = productPricingPlanPaymentScheduleResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SiteSummary> getSiteSummaryList() {
	 	return siteSummaryList;
	 }  
	 
	 public void setSiteSummaryList(List<SiteSummary>  siteSummaryList) {
	 	this.siteSummaryList = siteSummaryList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ReportIntValueItem> getReportIntValueItemList() {
	 	return reportIntValueItemList;
	 }  
	 
	 public void setReportIntValueItemList(List<ReportIntValueItem>  reportIntValueItemList) {
	 	this.reportIntValueItemList = reportIntValueItemList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ActiveSubscriptionsCountResponse> getActiveSubscriptionsCountResponseList() {
	 	return activeSubscriptionsCountResponseList;
	 }  
	 
	 public void setActiveSubscriptionsCountResponseList(List<ActiveSubscriptionsCountResponse>  activeSubscriptionsCountResponseList) {
	 	this.activeSubscriptionsCountResponseList = activeSubscriptionsCountResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<TotalSubscribersCountResponse> getTotalSubscribersCountResponseList() {
	 	return totalSubscribersCountResponseList;
	 }  
	 
	 public void setTotalSubscribersCountResponseList(List<TotalSubscribersCountResponse>  totalSubscribersCountResponseList) {
	 	this.totalSubscribersCountResponseList = totalSubscribersCountResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<RevenueAmount> getRevenueAmountList() {
	 	return revenueAmountList;
	 }  
	 
	 public void setRevenueAmountList(List<RevenueAmount>  revenueAmountList) {
	 	this.revenueAmountList = revenueAmountList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductsSignups> getProductsSignupsList() {
	 	return productsSignupsList;
	 }  
	 
	 public void setProductsSignupsList(List<ProductsSignups>  productsSignupsList) {
	 	this.productsSignupsList = productsSignupsList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ProductsRevenues> getProductsRevenuesList() {
	 	return productsRevenuesList;
	 }  
	 
	 public void setProductsRevenuesList(List<ProductsRevenues>  productsRevenuesList) {
	 	this.productsRevenuesList = productsRevenuesList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ReportDecimalValueItem> getReportDecimalValueItemList() {
	 	return reportDecimalValueItemList;
	 }  
	 
	 public void setReportDecimalValueItemList(List<ReportDecimalValueItem>  reportDecimalValueItemList) {
	 	this.reportDecimalValueItemList = reportDecimalValueItemList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<TodayNewSubscribersCountResponse> getTodayNewSubscribersCountResponseList() {
	 	return todayNewSubscribersCountResponseList;
	 }  
	 
	 public void setTodayNewSubscribersCountResponseList(List<TodayNewSubscribersCountResponse>  todayNewSubscribersCountResponseList) {
	 	this.todayNewSubscribersCountResponseList = todayNewSubscribersCountResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<Statement> getStatementList() {
	 	return statementList;
	 }  
	 
	 public void setStatementList(List<Statement>  statementList) {
	 	this.statementList = statementList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<StatementDetail> getStatementDetailList() {
	 	return statementDetailList;
	 }  
	 
	 public void setStatementDetailList(List<StatementDetail>  statementDetailList) {
	 	this.statementDetailList = statementDetailList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionRequest> getSubscriptionRequestList() {
	 	return subscriptionRequestList;
	 }  
	 
	 public void setSubscriptionRequestList(List<SubscriptionRequest>  subscriptionRequestList) {
	 	this.subscriptionRequestList = subscriptionRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionResponse> getSubscriptionResponseList() {
	 	return subscriptionResponseList;
	 }  
	 
	 public void setSubscriptionResponseList(List<SubscriptionResponse>  subscriptionResponseList) {
	 	this.subscriptionResponseList = subscriptionResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ServiceResult> getServiceResultList() {
	 	return serviceResultList;
	 }  
	 
	 public void setServiceResultList(List<ServiceResult>  serviceResultList) {
	 	this.serviceResultList = serviceResultList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<Currency> getCurrencyList() {
	 	return currencyList;
	 }  
	 
	 public void setCurrencyList(List<Currency>  currencyList) {
	 	this.currencyList = currencyList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<CancellationRequest> getCancellationRequestList() {
	 	return cancellationRequestList;
	 }  
	 
	 public void setCancellationRequestList(List<CancellationRequest>  cancellationRequestList) {
	 	this.cancellationRequestList = cancellationRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionItemHistoryResponse> getSubscriptionItemHistoryResponseList() {
	 	return subscriptionItemHistoryResponseList;
	 }  
	 
	 public void setSubscriptionItemHistoryResponseList(List<SubscriptionItemHistoryResponse>  subscriptionItemHistoryResponseList) {
	 	this.subscriptionItemHistoryResponseList = subscriptionItemHistoryResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionItemResponse> getSubscriptionItemResponseList() {
	 	return subscriptionItemResponseList;
	 }  
	 
	 public void setSubscriptionItemResponseList(List<SubscriptionItemResponse>  subscriptionItemResponseList) {
	 	this.subscriptionItemResponseList = subscriptionItemResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<TransactionResponse> getTransactionResponseList() {
	 	return transactionResponseList;
	 }  
	 
	 public void setTransactionResponseList(List<TransactionResponse>  transactionResponseList) {
	 	this.transactionResponseList = transactionResponseList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<SubscriptionItemRequest> getSubscriptionItemRequestList() {
	 	return subscriptionItemRequestList;
	 }  
	 
	 public void setSubscriptionItemRequestList(List<SubscriptionItemRequest>  subscriptionItemRequestList) {
	 	this.subscriptionItemRequestList = subscriptionItemRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<ChargeRequest> getChargeRequestList() {
	 	return chargeRequestList;
	 }  
	 
	 public void setChargeRequestList(List<ChargeRequest>  chargeRequestList) {
	 	this.chargeRequestList = chargeRequestList;
	 }


	/**
	 * 
	 * 
	 * 
	 */
	 public List<EventData> getEventDataList() {
	 	return eventDataList;
	 }  
	 
	 public void setEventDataList(List<EventData>  eventDataList) {
	 	this.eventDataList = eventDataList;
	 }


}