/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

 package com.dynabic.sdk.java.api;


import com.dynabic.sdk.java.model.*;

import org.codehaus.jackson.map.DeserializationConfig.Feature;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.type.TypeReference;
import com.wordnik.swagger.runtime.annotations.*;
import com.wordnik.swagger.runtime.common.*;
import com.wordnik.swagger.runtime.exception.*;

import java.util.*;
import java.lang.Long;
import java.io.IOException;


/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 * @author ramesh
 *
 */
public class ProductsAPI extends Object {

    private static APIInvoker apiInvoker = null;

	/**
	 * GetProductsBySite
	 *
	 * 
	 * 
     * @param siteSubdomain  site Subdomain
     *  @param isArchived  is Archived
     *  @param pageNumber  page number
     *  @param pageSize  page size
     *  
	 * @return List<ProductResponse> {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="siteSubdomain, isArchived, pageNumber, pageSize")
	 public static List<ProductResponse> GetProductsBySite(String siteSubdomain, String isArchived, String pageNumber, String pageSize) throws APIException {

		//parse inputs
		String  resourcePath = "/products/bysite/{siteSubdomain}/{format}?isArchived={isArchived}&pageNumber={pageNumber}&pageSize={pageSize}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( siteSubdomain != null) {
			resourcePath = resourcePath.replace("{siteSubdomain}", APIInvoker.toPathValue(siteSubdomain));
		}
		if( isArchived != null) {
			resourcePath = resourcePath.replace("{isArchived}", APIInvoker.toPathValue(isArchived));
		}
		if( pageNumber != null) {
			resourcePath = resourcePath.replace("{pageNumber}", APIInvoker.toPathValue(pageNumber));
		}
		if( pageSize != null) {
			resourcePath = resourcePath.replace("{pageSize}", APIInvoker.toPathValue(pageSize));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
        TypeReference<ArrayList<ProductResponse>> typeRef = new TypeReference<ArrayList<ProductResponse>>() {};
        try {
            List<ProductResponse> responseObject = (List<ProductResponse>) getApiInvoker().mapper.readValue(response, typeRef);
            return responseObject;
        } catch (IOException ioe) {
        	String[] args = new String[]{response, typeRef.toString()};
            throw new APIException(APIExceptionCodes.ERROR_CONVERTING_JSON_TO_JAVA, args, "Error in converting response json value to java object : " + ioe.getMessage(), ioe);
        }	}

	/**
	 * GetProductsBySiteAndFamily
	 *
	 * 
	 * 
     * @param siteSubdomain  site Subdomain
     *  @param productFamilyName  product Family Name
     *  @param isArchived  is Archived
     *  
	 * @return List<ProductResponse> {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="siteSubdomain, productFamilyName, isArchived")
	 public static List<ProductResponse> GetProductsBySiteAndFamily(String siteSubdomain, String productFamilyName, String isArchived) throws APIException {

		//parse inputs
		String  resourcePath = "/products/bysite/{siteSubdomain}/[{productFamilyName}]/{format}?isArchived={isArchived}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( siteSubdomain != null) {
			resourcePath = resourcePath.replace("{siteSubdomain}", APIInvoker.toPathValue(siteSubdomain));
		}
		if( productFamilyName != null) {
			resourcePath = resourcePath.replace("{productFamilyName}", APIInvoker.toPathValue(productFamilyName));
		}
		if( isArchived != null) {
			resourcePath = resourcePath.replace("{isArchived}", APIInvoker.toPathValue(isArchived));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
        TypeReference<ArrayList<ProductResponse>> typeRef = new TypeReference<ArrayList<ProductResponse>>() {};
        try {
            List<ProductResponse> responseObject = (List<ProductResponse>) getApiInvoker().mapper.readValue(response, typeRef);
            return responseObject;
        } catch (IOException ioe) {
        	String[] args = new String[]{response, typeRef.toString()};
            throw new APIException(APIExceptionCodes.ERROR_CONVERTING_JSON_TO_JAVA, args, "Error in converting response json value to java object : " + ioe.getMessage(), ioe);
        }	}

	/**
	 * GetProductsBySiteAndProductName
	 *
	 * 
	 * 
     * @param siteSubdomain  site Subdomain
     *  @param productName  product Name
     *  
	 * @return List<ProductResponse> {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="siteSubdomain, productName")
	 public static List<ProductResponse> GetProductsBySiteAndProductName(String siteSubdomain, String productName) throws APIException {

		//parse inputs
		String  resourcePath = "/products/bysite/{siteSubdomain}/[{productName}].{format}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( siteSubdomain != null) {
			resourcePath = resourcePath.replace("{siteSubdomain}", APIInvoker.toPathValue(siteSubdomain));
		}
		if( productName != null) {
			resourcePath = resourcePath.replace("{productName}", APIInvoker.toPathValue(productName));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
        TypeReference<ArrayList<ProductResponse>> typeRef = new TypeReference<ArrayList<ProductResponse>>() {};
        try {
            List<ProductResponse> responseObject = (List<ProductResponse>) getApiInvoker().mapper.readValue(response, typeRef);
            return responseObject;
        } catch (IOException ioe) {
        	String[] args = new String[]{response, typeRef.toString()};
            throw new APIException(APIExceptionCodes.ERROR_CONVERTING_JSON_TO_JAVA, args, "Error in converting response json value to java object : " + ioe.getMessage(), ioe);
        }	}

	/**
	 * GetProductByApiRef
	 *
	 * 
	 * 
     * @param siteId  site Id
     *  @param apiRef  api Ref
     *  
	 * @return ProductResponse {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="siteId, apiRef")
	 public static ProductResponse GetProductByApiRef(String siteId, String apiRef) throws APIException {

		//parse inputs
		String  resourcePath = "/products/byapiref/{siteId}/{apiRef}.{format}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( siteId != null) {
			resourcePath = resourcePath.replace("{siteId}", APIInvoker.toPathValue(siteId));
		}
		if( apiRef != null) {
			resourcePath = resourcePath.replace("{apiRef}", APIInvoker.toPathValue(apiRef));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
		//create output objects if the response has more than one object
		ProductResponse responseObject = (ProductResponse) getApiInvoker().deserialize(response, ProductResponse.class);
		return responseObject;
	}

	/**
	 * GetProductsByFamilyId
	 *
	 * 
	 * 
     * @param productFamilyId  product Family Id
     *  @param isArchived  is Archived
     *  
	 * @return List<ProductResponse> {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="productFamilyId, isArchived")
	 public static List<ProductResponse> GetProductsByFamilyId(String productFamilyId, String isArchived) throws APIException {

		//parse inputs
		String  resourcePath = "/products/byfamily/{productFamilyId}/{format}?isArchived={isArchived}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productFamilyId != null) {
			resourcePath = resourcePath.replace("{productFamilyId}", APIInvoker.toPathValue(productFamilyId));
		}
		if( isArchived != null) {
			resourcePath = resourcePath.replace("{isArchived}", APIInvoker.toPathValue(isArchived));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
        TypeReference<ArrayList<ProductResponse>> typeRef = new TypeReference<ArrayList<ProductResponse>>() {};
        try {
            List<ProductResponse> responseObject = (List<ProductResponse>) getApiInvoker().mapper.readValue(response, typeRef);
            return responseObject;
        } catch (IOException ioe) {
        	String[] args = new String[]{response, typeRef.toString()};
            throw new APIException(APIExceptionCodes.ERROR_CONVERTING_JSON_TO_JAVA, args, "Error in converting response json value to java object : " + ioe.getMessage(), ioe);
        }	}

	/**
	 * GetProductByFamilyIdAndProductName
	 *
	 * 
	 * 
     * @param productFamilyId  product Family Id
     *  @param productName  product Name
     *  
	 * @return ProductResponse {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="productFamilyId, productName")
	 public static ProductResponse GetProductByFamilyIdAndProductName(String productFamilyId, String productName) throws APIException {

		//parse inputs
		String  resourcePath = "/products/byfamily/{productFamilyId}/[{productName}].{format}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productFamilyId != null) {
			resourcePath = resourcePath.replace("{productFamilyId}", APIInvoker.toPathValue(productFamilyId));
		}
		if( productName != null) {
			resourcePath = resourcePath.replace("{productName}", APIInvoker.toPathValue(productName));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
		//create output objects if the response has more than one object
		ProductResponse responseObject = (ProductResponse) getApiInvoker().deserialize(response, ProductResponse.class);
		return responseObject;
	}

	/**
	 * GetProductById
	 *
	 * 
	 * 
     * @param productId  product Id
     *  
	 * @return ProductResponse {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="productId")
	 public static ProductResponse GetProductById(String productId) throws APIException {

		//parse inputs
		String  resourcePath = "/products/{productId}.{format}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "GET";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productId != null) {
			resourcePath = resourcePath.replace("{productId}", APIInvoker.toPathValue(productId));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
		//create output objects if the response has more than one object
		ProductResponse responseObject = (ProductResponse) getApiInvoker().deserialize(response, ProductResponse.class);
		return responseObject;
	}

	/**
	 * AddProduct
	 *
	 * 
	 * 
     * @param postData  new Product
     *  
	 * @return ProductResponse {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="postData")
	 public static ProductResponse AddProduct(ProductRequest postData) throws APIException {

		//parse inputs
		String  resourcePath = "/products/{format}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "POST";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, postData, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
		//create output objects if the response has more than one object
		ProductResponse responseObject = (ProductResponse) getApiInvoker().deserialize(response, ProductResponse.class);
		return responseObject;
	}

	/**
	 * UpdateProduct
	 *
	 * 
	 * 
     * @param postData  updated Product
     *  @param productId  product Id
     *  
	 * @return ProductResponse {@link ProductResponse} 
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="postData, productId")
	 public static ProductResponse UpdateProduct(ProductRequest postData, String productId) throws APIException {

		//parse inputs
		String  resourcePath = "/products/{productId}.{format}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "PUT";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productId != null) {
			resourcePath = resourcePath.replace("{productId}", APIInvoker.toPathValue(productId));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, postData, headerParams);
        if(response == null || response.length() == 0){
            return null;
        }
		//create output objects if the response has more than one object
		ProductResponse responseObject = (ProductResponse) getApiInvoker().deserialize(response, ProductResponse.class);
		return responseObject;
	}

	/**
	 * DeleteProduct
	 *
	 * 
	 * 
     * @param productId  product Id
     *  
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="productId")
	 public static void DeleteProduct(String productId) throws APIException {

		//parse inputs
		String  resourcePath = "/products/{productId}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "POST";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productId != null) {
			resourcePath = resourcePath.replace("{productId}", APIInvoker.toPathValue(productId));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
	}

	/**
	 * ArchiveProduct
	 *
	 * 
	 * 
     * @param productId  product Id
     *  
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="productId")
	 public static void ArchiveProduct(String productId) throws APIException {

		//parse inputs
		String  resourcePath = "/products/archive/{productId}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "PUT";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productId != null) {
			resourcePath = resourcePath.replace("{productId}", APIInvoker.toPathValue(productId));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
	}

	/**
	 * ActivateProduct
	 *
	 * 
	 * 
     * @param productId  product Id
     *  
	 * @throws APIException 
	 */
	 @MethodArgumentNames(value="productId")
	 public static void ActivateProduct(String productId) throws APIException {

		//parse inputs
		String  resourcePath = "/products/activate/{productId}";
		resourcePath = resourcePath.replace("{format}","json").replaceAll("\\*", "");
		String method = "PUT";
		Map<String, String> queryParams = new HashMap<String, String>();
		Map<String, String> headerParams = new HashMap<String, String>();
		if( productId != null) {
			resourcePath = resourcePath.replace("{productId}", APIInvoker.toPathValue(productId));
		}

        resourcePath = resourcePath.replaceAll("\\{\\w*\\}", "");

		//make the API Call
		String response = getApiInvoker().invokeAPI(resourcePath, method, queryParams, null, headerParams);
	}



    public static APIInvoker getApiInvoker() {
        if(apiInvoker == null){
            apiInvoker = APIInvoker.getApiInvoker();
        }
        return apiInvoker;
    }

    public static void setApiInvoker(APIInvoker invoker) {
        apiInvoker = invoker;
    }

}